name: Changelog
on:
  pull_request:
    branches:
      - main
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add Changelog